ARG profiles_default=default

FROM gcr.io/distroless/java17-debian11
#FROM amazoncorretto:17

ENV TZ ${TZ}

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

ARG profiles_default
ARG app
ENV SPRING_PROFILES_ACTIVE=$profiles_default
ENV APP=$app
#RUN echo ${SPRING_PROFILES_ACTIVE}
#RUN echo ${APP}

WORKDIR /app
#COPY ../$APP/target/*.jar /app.jar
COPY ../$APP/target/*.jar /app/app.jar

CMD ["app.jar"]
#CMD ["java", "-jar", "/app.jar"]